"""add candidate details to resumes

Revision ID: be90b74c4dc5
Revises: d545a973fa17
Create Date: 2026-09-06 23:47:37.219965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be90b74c4dc5'
down_revision: Union[str, Sequence[str], None] = 'd545a973fa17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('candidate_name', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('candidate_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'candidate_email')
    op.drop_column('resumes', 'candidate_name')
    # ### end Alembic commands ###
